[tool]
id = "com.loosewire.kelp"
label = "Kelp"
versionCode = 7
versionName = "0.2.5"
permissions = ["android.permission.INTERNET"]
capabilities = ["detached-audio"]
serverPackage = "com.loosewire.kelp"
orientation = "portrait"
icon = "@mipmap/ic_kelp_launcher"
